version: '3.9'

services:
  web.crm.io:
    build: .
    restart: always
    command: gunicorn --workers 3 --bind 0.0.0.0:5000 -m 007 runserver:venone_app
    volumes:
      - .:/venone
    ports:
      - "5000:5000"
    env_file:
      - ./.flaskenv
    depends_on:
      - db.postgres.io

  db.postgres.io:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.flaskenv
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  server.nginx.io:
    build: ./nginx
    restart: always
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - web.crm.io

volumes:
  postgres_data:
