"""Initial migration

Revision ID: aad4530a2cd4
Revises: 
Create Date: 2026-02-22 06:48:10.858342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aad4530a2cd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_permissions', sa.Integer(), nullable=True),
    sa.Column('role_name', sa.String(length=64), nullable=True),
    sa.Column('role_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_name', name=op.f('uq_roles_role_name'))
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_roles_role_default'), ['role_default'], unique=False)

    op.create_table('user',
    sa.Column('vn_country', sa.String(length=80), nullable=False),
    sa.Column('vn_avatar', sa.String(length=80), nullable=True),
    sa.Column('vn_password', sa.String(length=180), nullable=False),
    sa.Column('vn_birthdate', sa.Date(), nullable=True),
    sa.Column('vn_last_seen', sa.DateTime(), nullable=True),
    sa.Column('vn_house_owner', sa.Boolean(), nullable=True),
    sa.Column('vn_company', sa.Boolean(), nullable=True),
    sa.Column('vn_balance', sa.Float(), nullable=True),
    sa.Column('vn_device', sa.String(length=80), nullable=True),
    sa.Column('vn_find_us', sa.String(length=100), nullable=True),
    sa.Column('vn_ip_address', sa.String(length=50), nullable=True),
    sa.Column('vn_role_id', sa.Integer(), nullable=True),
    sa.Column('vn_gender', sa.String(length=10), nullable=True),
    sa.Column('vn_fullname', sa.String(length=80), nullable=False),
    sa.Column('vn_addr_email', sa.String(length=80), nullable=False),
    sa.Column('vn_profession', sa.String(length=100), nullable=True),
    sa.Column('vn_parent_name', sa.String(length=80), nullable=True),
    sa.Column('vn_phonenumber_one', sa.String(length=20), nullable=False),
    sa.Column('vn_phonenumber_two', sa.String(length=20), nullable=True),
    sa.Column('vn_cni_number', sa.String(length=80), nullable=True),
    sa.Column('vn_location', sa.String(length=180), nullable=True),
    sa.Column('vn_activated', sa.Boolean(), nullable=True),
    sa.Column('vn_agencie_name', sa.String(length=80), nullable=True),
    sa.Column('vn_business_number', sa.String(length=80), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_role_id'], ['roles.id'], name=op.f('fk_user_vn_role_id_roles'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('vn_addr_email', name=op.f('uq_user_vn_addr_email')),
    sa.UniqueConstraint('vn_agencie_name', name=op.f('uq_user_vn_agencie_name')),
    sa.UniqueConstraint('vn_business_number', name=op.f('uq_user_vn_business_number')),
    sa.UniqueConstraint('vn_phonenumber_one', name=op.f('uq_user_vn_phonenumber_one'))
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_uuid'), ['uuid'], unique=False)

    op.create_table('houseowner',
    sa.Column('vn_owner_id', sa.String(length=5), nullable=True),
    sa.Column('vn_avatar', sa.String(length=80), nullable=True),
    sa.Column('vn_user_id', sa.Integer(), nullable=True),
    sa.Column('vn_owner_percent', sa.Float(), nullable=True),
    sa.Column('vn_gender', sa.String(length=10), nullable=True),
    sa.Column('vn_fullname', sa.String(length=80), nullable=False),
    sa.Column('vn_addr_email', sa.String(length=80), nullable=False),
    sa.Column('vn_profession', sa.String(length=100), nullable=True),
    sa.Column('vn_parent_name', sa.String(length=80), nullable=True),
    sa.Column('vn_phonenumber_one', sa.String(length=20), nullable=False),
    sa.Column('vn_phonenumber_two', sa.String(length=20), nullable=True),
    sa.Column('vn_cni_number', sa.String(length=80), nullable=True),
    sa.Column('vn_location', sa.String(length=180), nullable=True),
    sa.Column('vn_activated', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_user_id'], ['user.id'], name=op.f('fk_houseowner_vn_user_id_user'), ondelete='cascade'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_houseowner')),
    sa.UniqueConstraint('vn_addr_email', name=op.f('uq_houseowner_vn_addr_email')),
    sa.UniqueConstraint('vn_owner_id', name=op.f('uq_houseowner_vn_owner_id')),
    sa.UniqueConstraint('vn_phonenumber_one', name=op.f('uq_houseowner_vn_phonenumber_one'))
    )
    with op.batch_alter_table('houseowner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_houseowner_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_houseowner_uuid'), ['uuid'], unique=False)

    op.create_table('percent',
    sa.Column('vn_user_id', sa.Integer(), nullable=False),
    sa.Column('vn_owner_percent', sa.Float(), nullable=True),
    sa.Column('vn_company_percent', sa.Float(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_user_id'], ['user.id'], name=op.f('fk_percent_vn_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_percent')),
    sa.UniqueConstraint('vn_user_id', name=op.f('uq_percent_vn_user_id'))
    )
    with op.batch_alter_table('percent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_percent_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_percent_uuid'), ['uuid'], unique=False)

    op.create_table('transfer_request',
    sa.Column('vn_transfer_id', sa.String(length=5), nullable=True),
    sa.Column('vn_user_id', sa.Integer(), nullable=False),
    sa.Column('vn_trans_amount', sa.Float(), nullable=False),
    sa.Column('vn_trans_status', sa.Boolean(), nullable=True),
    sa.Column('vn_withdrawal_number', sa.String(length=50), nullable=True),
    sa.Column('vn_withdrawal_method', sa.String(length=50), nullable=True),
    sa.Column('vn_cinetpay_data', sa.JSON(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_user_id'], ['user.id'], name=op.f('fk_transfer_request_vn_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_request')),
    sa.UniqueConstraint('vn_transfer_id', name=op.f('uq_transfer_request_vn_transfer_id'))
    )
    with op.batch_alter_table('transfer_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transfer_request_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_transfer_request_uuid'), ['uuid'], unique=False)

    op.create_table('house',
    sa.Column('vn_house_id', sa.String(length=5), nullable=False),
    sa.Column('vn_house_type', sa.String(length=80), nullable=False),
    sa.Column('vn_house_rent', sa.Float(), nullable=False),
    sa.Column('vn_house_guaranty', sa.Float(), nullable=False),
    sa.Column('vn_house_month', sa.Integer(), nullable=False),
    sa.Column('vn_house_number_room', sa.Integer(), nullable=False),
    sa.Column('vn_house_address', sa.String(length=120), nullable=False),
    sa.Column('vn_house_is_open', sa.Boolean(), nullable=False),
    sa.Column('vn_house_lease_start_date', sa.Date(), nullable=True),
    sa.Column('vn_house_lease_end_date', sa.Date(), nullable=True),
    sa.Column('vn_user_id', sa.Integer(), nullable=True),
    sa.Column('vn_owner_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_owner_id'], ['houseowner.id'], name=op.f('fk_house_vn_owner_id_houseowner')),
    sa.ForeignKeyConstraint(['vn_user_id'], ['user.id'], name=op.f('fk_house_vn_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_house')),
    sa.UniqueConstraint('vn_house_id', name=op.f('uq_house_vn_house_id'))
    )
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_house_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_house_uuid'), ['uuid'], unique=False)

    op.create_table('tenant',
    sa.Column('vn_tenant_id', sa.String(length=5), nullable=False),
    sa.Column('vn_birthdate', sa.Date(), nullable=True),
    sa.Column('vn_user_id', sa.Integer(), nullable=True),
    sa.Column('vn_house_id', sa.Integer(), nullable=True),
    sa.Column('vn_owner_id', sa.Integer(), nullable=True),
    sa.Column('vn_gender', sa.String(length=10), nullable=True),
    sa.Column('vn_fullname', sa.String(length=80), nullable=False),
    sa.Column('vn_addr_email', sa.String(length=80), nullable=False),
    sa.Column('vn_profession', sa.String(length=100), nullable=True),
    sa.Column('vn_parent_name', sa.String(length=80), nullable=True),
    sa.Column('vn_phonenumber_one', sa.String(length=20), nullable=False),
    sa.Column('vn_phonenumber_two', sa.String(length=20), nullable=True),
    sa.Column('vn_cni_number', sa.String(length=80), nullable=True),
    sa.Column('vn_location', sa.String(length=180), nullable=True),
    sa.Column('vn_activated', sa.Boolean(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_house_id'], ['house.id'], name=op.f('fk_tenant_vn_house_id_house')),
    sa.ForeignKeyConstraint(['vn_owner_id'], ['houseowner.id'], name=op.f('fk_tenant_vn_owner_id_houseowner')),
    sa.ForeignKeyConstraint(['vn_user_id'], ['user.id'], name=op.f('fk_tenant_vn_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant')),
    sa.UniqueConstraint('vn_addr_email', name=op.f('uq_tenant_vn_addr_email')),
    sa.UniqueConstraint('vn_phonenumber_one', name=op.f('uq_tenant_vn_phonenumber_one')),
    sa.UniqueConstraint('vn_tenant_id', name=op.f('uq_tenant_vn_tenant_id'))
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenant_uuid'), ['uuid'], unique=False)

    op.create_table('payment',
    sa.Column('vn_payment_id', sa.String(length=5), nullable=True),
    sa.Column('vn_transaction_id', sa.String(length=10), nullable=True),
    sa.Column('vn_pay_amount', sa.Float(), nullable=False),
    sa.Column('vn_pay_late_penalty', sa.Float(), nullable=True),
    sa.Column('vn_pay_date', sa.Date(), nullable=False),
    sa.Column('vn_pay_status', sa.Boolean(), nullable=True),
    sa.Column('vn_cinetpay_data', sa.JSON(), nullable=True),
    sa.Column('vn_payee_id', sa.Integer(), nullable=True),
    sa.Column('vn_owner_id', sa.Integer(), nullable=True),
    sa.Column('vn_tenant_id', sa.Integer(), nullable=True),
    sa.Column('vn_house_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=40), nullable=True),
    sa.Column('vn_created_at', sa.DateTime(), nullable=True),
    sa.Column('vn_updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vn_house_id'], ['house.id'], name=op.f('fk_payment_vn_house_id_house')),
    sa.ForeignKeyConstraint(['vn_owner_id'], ['houseowner.id'], name=op.f('fk_payment_vn_owner_id_houseowner')),
    sa.ForeignKeyConstraint(['vn_payee_id'], ['user.id'], name=op.f('fk_payment_vn_payee_id_user')),
    sa.ForeignKeyConstraint(['vn_tenant_id'], ['tenant.id'], name=op.f('fk_payment_vn_tenant_id_tenant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment')),
    sa.UniqueConstraint('vn_payment_id', name=op.f('uq_payment_vn_payment_id')),
    sa.UniqueConstraint('vn_transaction_id', name=op.f('uq_payment_vn_transaction_id'))
    )
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_id'), ['id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_uuid'), ['uuid'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_uuid'))
        batch_op.drop_index(batch_op.f('ix_payment_id'))

    op.drop_table('payment')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_uuid'))
        batch_op.drop_index(batch_op.f('ix_tenant_id'))

    op.drop_table('tenant')
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_house_uuid'))
        batch_op.drop_index(batch_op.f('ix_house_id'))

    op.drop_table('house')
    with op.batch_alter_table('transfer_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transfer_request_uuid'))
        batch_op.drop_index(batch_op.f('ix_transfer_request_id'))

    op.drop_table('transfer_request')
    with op.batch_alter_table('percent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_percent_uuid'))
        batch_op.drop_index(batch_op.f('ix_percent_id'))

    op.drop_table('percent')
    with op.batch_alter_table('houseowner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_houseowner_uuid'))
        batch_op.drop_index(batch_op.f('ix_houseowner_id'))

    op.drop_table('houseowner')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_uuid'))
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_role_default'))
        batch_op.drop_index(batch_op.f('ix_roles_id'))

    op.drop_table('roles')
    # ### end Alembic commands ###
