name: Pull Request

on:
  pull_request:
    branches:
      - dev

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configuration
        run: |
          git config --global user.email "geekactux@gmail.com"
          git config --global user.name "flavien-hugs"

      - name: git add
        run: |
          git add -A
          ls -la

      - name: commit and push
        run: |
          git commit -m "branch are updated"
          git push
